SET SQL_SAFE_UPDATES=0;
SET foreign_key_checks = 0;
DELETE FROM icaras.adres;
DELETE FROM icaras.bedrijf;
DELETE FROM icaras.digitaal_adres;
DELETE FROM icaras.identiteitsbewijs;
DELETE FROM icaras.persoon;
DELETE FROM icaras.persoonsrol;
DELETE FROM icaras.bedrijf_expertise;
COMMIT;
SET SQL_SAFE_UPDATES=1;
SET foreign_key_checks = 1;
